#for AWINIC AW87XXX Smart K PA
obj-$(CONFIG_SND_SOC_AW87XXX) += aw87xxx.o
obj-$(CONFIG_SND_SOC_AW87XXX) += aw87xxx_device.o
obj-$(CONFIG_SND_SOC_AW87XXX) += aw87xxx_monitor.o
obj-$(CONFIG_SND_SOC_AW87XXX) += aw87xxx_bin_parse.o
obj-$(CONFIG_SND_SOC_AW87XXX) += aw87xxx_dsp.o
obj-$(CONFIG_SND_SOC_AW87XXX) += aw87xxx_acf_bin.o