# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_HS_OCH165T)  		+= och165t_hall.o
obj-$(CONFIG_HS_MH248)  		+= mh248.o
obj-$(CONFIG_HS_WH2506D)  		+= wh2506d.o
obj-$(CONFIG_HS_HTGPIOHALL)  		+= htgpio_hall.o
